name: ⭐ Update here-be-stars
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

jobs:
  delete_old_runs:
    name: 🧹 Delete old workflow runs
    runs-on: ubuntu-latest
    
    steps:
      - name: 🧹 Delete old workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
          --paginate -q '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | "\(.id)"' | \
          xargs -n1 -I % gh api repos/${{ github.repository }}/actions/runs/% -X DELETE

  update-stars:
    name: ⭐ Update the stars repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
        
    steps:
      - name: ⬇ Checkout
        uses: actions/checkout@v3

      - name: 🔧 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🔧 Install dependencies
        run: |
          pip3 install --upgrade pip wheel setuptools
          pip3 install starred

      - name: 🔧 Checks
        run: |
          pip -V
          pip show starred

      - name: ⭐ Update stars README
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTIONS_BOT_NAME: 'github-actions[bot]'
          GITHUB_ACTIONS_BOT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
          COMMIT_MSG: "⭐ Github Stars update [Github Actions Cron]"
          
        run: |
          starred --username ${GITHUB_REPOSITORY_OWNER} --sort > README.md
          git add .
          git config user.name ${GITHUB_ACTIONS_BOT_NAME}
          git config user.email ${GITHUB_ACTIONS_BOT_EMAIL}
          git commit -am "⭐ Github Stars update [Github Actions Cron]"
          git push origin
        
#       - name: Push changes
#         uses: actions-go/push@master
#         with:
#           remote: origin
#           commit-message: "⭐ Github Stars update [Github Actions Cron]"
